# Generated by Django 3.1.4 on 2021-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='news_email',
            field=models.EmailField(max_length=50),
        ),
    ]
