# Generated by Django 3.1.4 on 2021-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20210221_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='news_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
