# Generated by Django 3.1.4 on 2021-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20210222_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='news_email',
            field=models.EmailField(max_length=50),
        ),
    ]
