# Generated by Django 3.1.4 on 2021-02-21 12:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_url', models.URLField(blank=True, max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('affiliation', models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Bussiness', 'Bussiness'), ('Non-profit', 'Non-profit'), ('Industry/Government', 'Industry/Government')], max_length=50, null=True)),
                ('profile_picture', models.ImageField(default='profile_picture/defaultphoto.png', null=True, upload_to='profile_picture')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
